# ----------- CONFIGURABLE START -----------
title:            "AlxRoooooose|Independent Developer"
description:      "强健其体魄，野蛮其精神"
url:              https://hzx4585.github.io # 域名
signoff:          "AlxRoooooose" # Your name
facebook_appid:   #liberxue
google_analytics: UA-101222464-1
share:            true
# 分页
paginate: 15
paginate_path: "liberxuepage:num"
gems: [jekyll-paginate]
links:
  - name:         BOOK
    url:          /book
    external:     false
  - name:         TEC
    url:          /road
    external:     false
  - name:         AIRBNB
    url:          /airbnb
    external:     false
  - name:         ARCHIVE
    url:          /archives
    external:     false
  - name:         TAG
    url:          /tags
    external:     false
  - name:         ABOUT
    url:          /about
    external:     false
# ------------ CONFIGURABLE END ------------

#permalink:        /:categories/:title.html
permalink: /:year/:month/:day/:title.html
defaults:
  - values:
      layout: "default"
